Document: flashpoint-infinity
Title: Debian flashpoint-infinity Manual
Author: <insert document author here>
Abstract: This manual describes what flashpoint-infinity is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/flashpoint-infinity/flashpoint-infinity.sgml.gz

Format: postscript
Files: /usr/share/doc/flashpoint-infinity/flashpoint-infinity.ps.gz

Format: text
Files: /usr/share/doc/flashpoint-infinity/flashpoint-infinity.text.gz

Format: HTML
Index: /usr/share/doc/flashpoint-infinity/html/index.html
Files: /usr/share/doc/flashpoint-infinity/html/*.html
